baseurl = "https://superphysics.org"
# metaDataFormat = "yaml"
title = "Superphysics"
theme = "blist"
logo = "/icons/sp.png"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true

paginate = 12


[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [[languages.en.menu.main]]
        name = "Research"
        url = "research"
        weight = 1
    [[languages.en.menu.main]]
        name = "Superphysics"
        url = "superphysics"
        weight = 2
    [[languages.en.menu.main]]
        name = "Material"
        url = "material/"
        weight = 3
    # [[languages.en.menu.main]]
    #     name = "Tags"
    #     url = "tags"
    #     weight = 3
    [[languages.de.menu.main]]
        name = "Bio"
        url = "bio"
        weight = 4
    [[languages.de.menu.main]]
        name = "Supersociology"
        url = "social/supersociology"
        weight = 5
    [[languages.de.menu.main]]
        name = "Supereconomics"
        url = "social/supereconomics"
        weight = 6
    [[languages.de.menu.main]]
        name = "Social Cycles"
        url = "social/cycles"
        weight = 7

  [languages.de]
    contentDir = "content/de"
    weight = 2
    languageName = "Deutsch"
    [[languages.de.menu.main]]
        name = "Research"
        url = "research"
        weight = 1
    [[languages.de.menu.main]]
        name = "Superphysics"
        url = "superphysics"
        weight = 2
    [[languages.de.menu.main]]
        name = "Material"
        url = "material"
        weight = 3
    [[languages.de.menu.main]]
        name = "Bio"
        url = "bio"
        weight = 4
    [[languages.de.menu.main]]
        name = "Supersociology"
        url = "social/supersociology"
        weight = 5
    [[languages.de.menu.main]]
        name = "Supereconomics"
        url = "social/supereconomics"
        weight = 6
    [[languages.de.menu.main]]
        name = "Social Cycles"
        url = "social/cycles"
        weight = 7

  [languages.fr]
    contentDir = "content/fr"
    weight = 1
    languageName = "Français"
    [[languages.fr.menu.main]]
        name = "Research"
        url = "research"
        weight = 1
    [[languages.fr.menu.main]]
        name = "Superphysics"
        url = "superphysics"
        weight = 2
    [[languages.fr.menu.main]]
        name = "Material"
        url = "material/"
        weight = 3

[ar]
    weight          = 2
    languageCode    = "ar"
    languageName    = "Arabic"
    contentDir      = "content/ar"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "الفيزياء الفائقة"
    [ar.params]
        author = "Pantrypoints Technologies"
        description = "نموذج علمي يعتمد على الموجات"


[zh]
    weight          = 3
    languageCode    = "zh"
    languageName    = "Chinese"
    contentDir      = "content/zh"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superphysics"
    [zh.params]
        author = "Pantrypoints Technologies"
        description = "超物理学：基于波动的科学范式"


[fr]
    weight          = 10
    languageCode    = "fr"
    languageName    = "French"
    contentDir      = "content/fr"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superphysique"
    [fr.params]
        author = "Pantrypoints Technologies"
        description = "Une Nouvelle Science Basée sur la Métaphysique et la Dialectique Socratique"



[de]
    weight          = 20
    languageCode    = "de"
    languageName    = "German"
    contentDir      = "content/de"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "SUPERPHYSIK"
    [de.params]
        author = "Pantrypoints Technologies"
        description = "Basierend auf der Dynamik der empfindungsfähigen Energie"


[id]
    weight          = 30
    languageCode    = "id"
    languageName    = "Indonesian"
    contentDir      = "content/id"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superfisika"
    [id.params]
        author = "Pantrypoints Technologies"
        description = "Ilmu Baru Berdasarkan Metafisika dan Dialektika Sokratik"



[jp]
    weight          = 40
    languageCode    = "jp"
    languageName    = "Japanese"
    contentDir      = "content/jp"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "超物理学"
    [jp.params]
        author = "Pantrypoints Technologies"
        description = "超物理学 -- 波動に基づく科学的パラダイム"

[kr]
    weight          = 45
    languageCode    = "kr"
    languageName    = "Korean"
    contentDir      = "content/kr"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "슈퍼물리학"
    [kr.params]
        author = "Pantrypoints Technologies"
        description = "슈퍼물리학 - 파동기반 과학 패러다임"


[pt]
    weight          = 47
    languageCode    = "pt"
    languageName    = "Portuguese"
    contentDir      = "content/pt"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superfísica"
    [pt.params]
        author = "Pantrypoints Technologies"
        description = "Paradigma Científico Baseado em Ondas"


[es]
    weight          = 50
    languageCode    = "es"
    languageName    = "Spanish"
    contentDir      = "content/es"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superfísica"
    [es.params]
        author = "Pantrypoints Technologies"
        description = "Paradigma científico basado en ondas"

[tl]
    weight          = 80
    languageCode    = "tl"
    languageName    = "Tagalog"
    contentDir      = "content/tl"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superphysics"
    [tl.params]
        author = "Pantrypoints Technologies"
        description = "Ang Superphysics ay bagong siyensya na base sa Metaphysics at Socratic Dialectics."

[vi]
    weight          = 90
    languageCode    = "vi"
    languageName    = "Vietnamese"
    contentDir      = "content/vi"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superphysics"
    [vi.params]
        author = "Pantrypoints Technologies"
        description = "Mô hình khoa học dựa trên sóng"


[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 | Pantrypoints Technologies"
  favicon = "/icons/sp30.png"

  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true


  hidePageThumbnail = false

# Comments system
[params.comments]
  system = "giscus"

  repo="jundalisay/superblist"
  repo-id="R_kgDOKk--Tw"
  category="General"
  category-id="DIC_kwDOKk--T84CacDf"
  mapping="pathname"
  strict="0"
  reactions-enabled="1"
  emit-metadata="0"
  input-position="bottom"
  theme="preferred_color_scheme"
  lang="en"
  crossorigin="anonymous"

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Follow us!"
  description = "We're building a new science and new systems for a better reality"

  [[params.homepage.social.icons]]
    website = "twitter"
    url = "https://twitter.com/superphysicsorg"
  # [[params.homepage.social.icons]]
  #   website = "linkedin"
  #   url = "https://linkedin.com/in/"
  # [[params.homepage.social.icons]]
  #   website = "xing"
  #   url = "https://www.xing.com/profile/"
  # [[params.homepage.social.icons]]
  #   website = "telegram"
  #   url = "https://t.me/"
  # [[params.homepage.social.icons]]
  #   website = "github"
  #   url = "https://github.com/"
  # [[params.homepage.social.icons]]
  #   website = "buymeacoffee"
  #   url = "https://www.buymeacoffee.com/"
  # [[params.homepage.social.icons]]
  #   website = "medium"
  #   url = "https://medium.com/"
  # [[params.homepage.social.icons]]
  #   website = "reddit"
  #   url = "https://reddit.com/"
  # [[params.homepage.social.icons]]
  #   website = "dribbble"
  #   url = "https://dribbble.com/"
  # [[params.homepage.social.icons]]
  #   website = "stackoverflow"
  #   url = "https://stackoverflow.com/"
  # [[params.homepage.social.icons]]
  #   website = "xda"
  #   url = "https://forum.xda-developers.com/"
  # [[params.homepage.social.icons]]
  #   website = "tiktok"
  #   url = "https://tiktok.com"
  # [[params.homepage.social.icons]]
  #   website = "googlescholar"
  #   url = "https://scholar.google.com/"
  # [[params.homepage.social.icons]]
  #   website = "mastodon"
  #   url = "https://joinmastodon.org"
  [[params.homepage.social.icons]]
    website = "youtube"
    url = "https://www.youtube.com/@superphysicsorg"
  # [[params.homepage.social.icons]]
  #   website = "instagram"
  #   url = "https://instagram.com"
  [[params.homepage.social.icons]]
    website = "facebook"
    url = "https://www.facebook.com/superphysicsorg"
  # [[params.homepage.social.icons]]
  #   website = "behance"
  #   url = "https://behance.net"

# [[menu.main]]
#   name = "About"
#   url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
