baseurl = "https://superphysics.org"
# metaDataFormat = "yaml"
title = "Superphysics"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false

paginate = 12


[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [[languages.en.menu.main]]
        name = "/icons/book.png"
        url = "research"
        weight = 1
    [[languages.en.menu.main]]
        identifier = "sp"
        name = "/icons/sp.png"
        url = "superphysics"
        weight = 2
    [[languages.en.menu.main]]
        name = "/icons/spmat.png"
        url = "material/"
        weight = 3
    # [[languages.en.menu.main]]
    #     name = "Tags"
    #     url = "tags"
    #     weight = 3
    [[languages.en.menu.main]]
        name = "/icons/spmed.png"
        url = "bio"
        weight = 4
    [[languages.en.menu.main]]
        name = "/icons/spsoc.png"
        url = "social/supersociology"
        weight = 5
    [[languages.en.menu.main]]
        name = "/icons/specon.png"
        url = "social/economics"
        weight = 6
    [[languages.en.menu.main]]
        name = "/icons/cycles.png"
        url = "social/cycles"
        weight = 7
    [[languages.en.menu.main]]
        name = "/icons/question.png"
        url = "faq"
        weight = 8
    [[languages.en.menu.main]]
        name = "/icons/about.png"
        url = "about"
        weight = 9
    [languages.en.params]
      heading = "A New Science Based on Metaphysics and Socratic Dialectics"
      intro = "Superphysics: Wave-based Scientific Paradigm"
      sub = "All Knowledge Can Be Grouped Into Three"
      banner = "/photos/physics/galaxy.jpg"
      youtube = "8bnws4po7ew"
    [languages.en.params.cards.a]
      icon = "/icons/tao.png"
      title = "Metaphysics"
      sub = "0-50% Replicable: Paradoxical"
    [languages.en.params.cards.b]
      icon = "/icons/sp.png"
      title = "Superphysics"
      sub = "51-99% Replicable: Subjective"
    [languages.en.params.cards.c]
      icon = "/icons/atom.png"
      title = "Physics"
      sub = "100% Replicable: Objective"
    [languages.en.params.tricon1]
      heading = "The Nature of the Soul"
      title = "Everything is a wave that manifests as a particle"
      sub = "The analog universe streams in real-definition to create reality"
      youtube = "dc4VNkfqs1s"
      icon = "/icons/sp.png"
      link= "/superphysics/principles"
    [languages.en.params.tricon1.items.a]
      url = "/superphysics/principles/chapter-01/"
      img= "/photos/physics/ai.jpg"
      title = "We're in a Matrix!"
      sub = "See how we can exist well in it"
    [languages.en.params.tricon1.items.b]
      url = "/superphysics/principles/chapter-02"
      img = "/photos/idea.jpg"
      title = "Everything is an Idea"
      sub = "Inside the Mind or Matrix"
    [languages.en.params.tricon1.items.c]
      url = "/superphysics/principles/chapter-04b"
      img = "/graphics/physics/math.jpg"
      title = "A New Math for a New Science"
      sub = "Has relativity baked in"
    [languages.en.params.tricon1.items.d]
      url = "/superphysics/principles/chapter-11"
      img = "/avatars/socrates.jpg"
      title = "Socratic Dialectics for Solving Problems"
      sub = "Do you have a problem? The solution already exists!"
    [languages.en.params.tricon2]
      heading = "The Soul of the Physical Universe"
      title = "Material Superphysics"
      sub = "Based on Descartes and the five layers of the ancient Greek, Hindus, and Chinese"
      youtube = "3l9J6tH4iD0"
      icon = "/icons/spmat.png"
      link= "/material/principles"
    [languages.en.params.tricon2.items.a]
      url = "/material/principles/intro/chapter-01"
      img= "/graphics/physics/aetherdrag.jpg"
      title = "The Five Layers of Superphysics"
      sub = "The Material, Radioactive, Radiant, Spatial, and Aethereal"
    [languages.en.params.tricon2.items.b]
      url = "/material/fallacies/general-relativity/"
      img= "/graphics/physics/general.jpg"
      title = "The Alternative to General Relativity"
      sub = "The Metaphysics of Spacetime"
    [languages.en.params.tricon2.items.c]
      url= "/material/principles/part-2/chapter-02/"
      img = "/photos/physics/quasar.jpg"
      title = "Aethereal Propulsion"
      sub = "We bring back the theory of gravity from Kepler and Descartes"
    [languages.en.params.tricon2.items.d]
      url = "/material/principles/part-3/chapter-02/"
      img= "/photos/physics/elec.jpg"
      title = "Electrons are Positive, Protons are Negative"
      sub= "We use male-female to avoid confusion"
    [languages.en.params.tricon3]
      heading = "The Soul of Living Entities"
      title = "Bio Superphysics"
      sub = "Based on the dynamics of the sentient energy"
      youtube= "Y6YKmtqJak4"
      icon = "/icons/spmed.png"
      link= "/bio/principles"
    [languages.en.params.tricon3.items.a]
      url = "/bio/principles/part-04/chapter-03/"
      img= "/photos/med/cancer2.jpg"
      title = "Cancers and Diseases Have Been Cured by Non-Western Medicine"
      sub = "See the wave-based alternatives to particle-based Western Medicine"
    [languages.en.params.tricon3.items.b]
      url = "/bio/principles/intro/chapter-01/"
      img= "/photos/psych/schizo.jpg"
      title = "You Have 3 Billion Selves"
      sub = "'You' are made up of a changing wave of 'yous'"
    [languages.en.params.tricon3.items.c]
      url = "/bio/smith-veg/"
      img= "/avatars/smithstatue.jpg"
      title = "Adam Smith the Vegetarian"
      sub = "He preferred vegetables, specifically potatoes, over meat"
    [languages.en.params.tricon3.items.d]
      url = "/bio/solutions/covid/"
      img= "/photos/med/covid.jpg"
      title = "How to Stop Covid"
      sub = "See how NATO could have stopped Covid back in 2020"
    [languages.en.params.tricon4]
      heading = "The Soul of Society"
      title = "Social Superphysics"
      sub = "Fellow-Feeling Instead of Selfish-Interest"
      youtube = "AfByl9Mywi4"
      icon = "/icons/spsoc.png"
    [languages.en.params.tricon4.items.a]
      url = "/social/supersociology/principles/part-1/chapter-01"
      img = "/photos/vanity.jpg"
      title = "The Ego is the Cause of Problems in Society"
      sub = "See how supersociology aims to fix it"
    [languages.en.params.tricon4.items.b]
      url = "/social/economics/principles/intro/chapter-03"
      img = "/photos/grains.jpg"
      title = "The Metaphysics of Value and the Four Laws of Value"
      sub = "Supereconomics deals with resource allocation and socio-economic issues"
    [languages.en.params.tricon4.items.c]
      url = "/social/supersociology/principles/part-1/chapter-05"
      img = "/photos/medieval/hitler.jpg"
      title = "The Socratic Law of Social Cycles"
      sub = "See how we use it to predict events like presidential elections and recessions"
    [languages.en.params.tricon4.items.d]
      url = "/social/cycles/"
      img= "/photos/ukraine.jpg"
      title = "Social Cycles Predictions"
      sub = "See our model's predictions for various countries"

  [languages.de]
    contentDir = "content/de"
    weight = 2
    languageName = "Deutsch"
    [[languages.de.menu.main]]
        name = "Research"
        url = "research"
        weight = 1
    [[languages.de.menu.main]]
        name = "Superphysics"
        url = "superphysics"
        weight = 2
    [[languages.de.menu.main]]
        name = "Material"
        url = "material"
        weight = 3
    [[languages.de.menu.main]]
        name = "Bio"
        url = "bio"
        weight = 4
    [[languages.de.menu.main]]
        name = "Supersociology"
        url = "social/supersociology"
        weight = 5
    [[languages.de.menu.main]]
        name = "Supereconomics"
        url = "social/supereconomics"
        weight = 6
    [[languages.de.menu.main]]
        name = "Social Cycles"
        url = "social/cycles"
        weight = 7

  [languages.fr]
    contentDir = "content/fr"
    weight = 1
    languageName = "Français"
    [[languages.fr.menu.main]]
        name = "Research"
        url = "research"
        weight = 1
    [[languages.fr.menu.main]]
        name = "Superphysics"
        url = "superphysics"
        weight = 2
    [[languages.fr.menu.main]]
        name = "Material"
        url = "material/"
        weight = 3

[ar]
    weight          = 2
    languageCode    = "ar"
    languageName    = "Arabic"
    contentDir      = "content/ar"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "الفيزياء الفائقة"
    [ar.params]
        author = "Pantrypoints Technologies"
        description = "نموذج علمي يعتمد على الموجات"


[zh]
    weight          = 3
    languageCode    = "zh"
    languageName    = "Chinese"
    contentDir      = "content/zh"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superphysics"
    [zh.params]
        author = "Pantrypoints Technologies"
        description = "超物理学：基于波动的科学范式"


[fr]
    weight          = 10
    languageCode    = "fr"
    languageName    = "French"
    contentDir      = "content/fr"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superphysique"
    [fr.params]
        author = "Pantrypoints Technologies"
        description = "Une Nouvelle Science Basée sur la Métaphysique et la Dialectique Socratique"



[de]
    weight          = 20
    languageCode    = "de"
    languageName    = "German"
    contentDir      = "content/de"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "SUPERPHYSIK"
    [de.params]
        author = "Pantrypoints Technologies"
        description = "Basierend auf der Dynamik der empfindungsfähigen Energie"


[id]
    weight          = 30
    languageCode    = "id"
    languageName    = "Indonesian"
    contentDir      = "content/id"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superfisika"
    [id.params]
        author = "Pantrypoints Technologies"
        description = "Ilmu Baru Berdasarkan Metafisika dan Dialektika Sokratik"



[jp]
    weight          = 40
    languageCode    = "jp"
    languageName    = "Japanese"
    contentDir      = "content/jp"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "超物理学"
    [jp.params]
        author = "Pantrypoints Technologies"
        description = "超物理学 -- 波動に基づく科学的パラダイム"

[kr]
    weight          = 45
    languageCode    = "kr"
    languageName    = "Korean"
    contentDir      = "content/kr"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "슈퍼물리학"
    [kr.params]
        author = "Pantrypoints Technologies"
        description = "슈퍼물리학 - 파동기반 과학 패러다임"


[pt]
    weight          = 47
    languageCode    = "pt"
    languageName    = "Portuguese"
    contentDir      = "content/pt"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superfísica"
    [pt.params]
        author = "Pantrypoints Technologies"
        description = "Paradigma Científico Baseado em Ondas"


[es]
    weight          = 50
    languageCode    = "es"
    languageName    = "Spanish"
    contentDir      = "content/es"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superfísica"
    [es.params]
        author = "Pantrypoints Technologies"
        description = "Paradigma científico basado en ondas"

[tl]
    weight          = 80
    languageCode    = "tl"
    languageName    = "Tagalog"
    contentDir      = "content/tl"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superphysics"
    [tl.params]
        author = "Pantrypoints Technologies"
        description = "Ang Superphysics ay bagong siyensya na base sa Metaphysics at Socratic Dialectics."

[vi]
    weight          = 90
    languageCode    = "vi"
    languageName    = "Vietnamese"
    contentDir      = "content/vi"
    copyright       = "&copy; 2023 Pantrypoints Technologies"
    title           = "Superphysics"
    [vi.params]
        author = "Pantrypoints Technologies"
        description = "Mô hình khoa học dựa trên sóng"


[params]
  logo = "/icons/sp.png"
  
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 | Pantrypoints Technologies"
  favicon = "/icons/sp30.png"

  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true


  hidePageThumbnail = false

# Comments system
[params.comments]
  system = "giscus"

  repo="jundalisay/superblist"
  repo-id="R_kgDOKk--Tw"
  category="General"
  category-id="DIC_kwDOKk--T84CacDf"
  mapping="pathname"
  strict="0"
  reactions-enabled="1"
  emit-metadata="0"
  input-position="bottom"
  theme="preferred_color_scheme"
  lang="en"
  crossorigin="anonymous"

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Follow us!"
  description = "We're building a new science and new systems for a better reality"

  [[params.homepage.social.icons]]
    website = "twitter"
    url = "https://twitter.com/superphysicsorg"
  # [[params.homepage.social.icons]]
  #   website = "linkedin"
  #   url = "https://linkedin.com/in/"
  # [[params.homepage.social.icons]]
  #   website = "xing"
  #   url = "https://www.xing.com/profile/"
  # [[params.homepage.social.icons]]
  #   website = "telegram"
  #   url = "https://t.me/"
  # [[params.homepage.social.icons]]
  #   website = "github"
  #   url = "https://github.com/"
  # [[params.homepage.social.icons]]
  #   website = "buymeacoffee"
  #   url = "https://www.buymeacoffee.com/"
  # [[params.homepage.social.icons]]
  #   website = "medium"
  #   url = "https://medium.com/"
  # [[params.homepage.social.icons]]
  #   website = "reddit"
  #   url = "https://reddit.com/"
  # [[params.homepage.social.icons]]
  #   website = "dribbble"
  #   url = "https://dribbble.com/"
  # [[params.homepage.social.icons]]
  #   website = "stackoverflow"
  #   url = "https://stackoverflow.com/"
  # [[params.homepage.social.icons]]
  #   website = "xda"
  #   url = "https://forum.xda-developers.com/"
  # [[params.homepage.social.icons]]
  #   website = "tiktok"
  #   url = "https://tiktok.com"
  # [[params.homepage.social.icons]]
  #   website = "googlescholar"
  #   url = "https://scholar.google.com/"
  # [[params.homepage.social.icons]]
  #   website = "mastodon"
  #   url = "https://joinmastodon.org"
  [[params.homepage.social.icons]]
    website = "youtube"
    url = "https://www.youtube.com/@superphysicsorg"
  # [[params.homepage.social.icons]]
  #   website = "instagram"
  #   url = "https://instagram.com"
  [[params.homepage.social.icons]]
    website = "facebook"
    url = "https://www.facebook.com/superphysicsorg"
  # [[params.homepage.social.icons]]
  #   website = "behance"
  #   url = "https://behance.net"

# [[menu.main]]
#   name = "About"
#   url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
